baseURL = "https://blog.orgs.top/"
title = "MyOnly"
theme = "PaperMod"
languageCode = "zh-cn"

[params]
  # PaperMod 基础参数（按需添加）
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "归档"
    url = "/posts/"
    weight = 2
